[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  external_node_modules = ["express"]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  
[[redirects]]
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
